name: app_navegacion_estado
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  provider: ^6.1.5+1
  http: ^1.2.2
  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  ui_components:
    path: packages/ui_components

    

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: 
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
